### ISSUE TITLE
Does not load the project

### ISSUE THREAD

**Issue by tiagodevweb** [pachecoio/go-todo#1]
Congratulations on the repository!
When uploading the environment I came across this error in the docker-compose logs:

**error layer=rpc rpc:invalid character 'G' looking for beginning of value**

Does not load the project in the browser

**Comment by sudoish** [comment]
Hey Tiago, thank you for your feedback!
I was not able to reproduce the error, could you send me the steps you took that resulted in this?

**Comment by tiagodevweb** [comment]
Actually it's when I access 2345, on 5000 everything seems to be ok, which uri from the swagger?

**Comment by sudoish** [comment]
The correct port to use the app is the `5000`.
The `2345` port is used for debugging purposes with delve. I hope that clarifies the issue.
